### ISSUE TITLE
Encryption/Decryption and Hashing Helper Functions

### ISSUE THREAD

**Issue by nelsonic** [dwyl/fields#10]
As a Developer implementing the Custom Ecto Types for the various Fields, 
I need several helper functions for Encrypting/Decrypting and Hashing 
so that I can re-use the common functionality across Ecto Types.

# Todo

Create the following "helper" functions:

+ [x] **`get_encryption_key/0`** should retrieve the _last_ item in the **`ENCRYPTION_KEYS`** Environment Variable List. 
  > **Note**: we should have the notion of "key rotation" built-in from day one. Even if people only define a _single_ Encryption Key, we need to make it _easy_ to define multiple keys "out of the box". see: https://github.com/dwyl/phoenix-ecto-encryption-example#encryption_keys-environment-variable and https://github.com/dwyl/phoenix-ecto-encryption-example#33-get-encryption-key
+ [x] **`get_encryption_key/1`** should be used when _decrypting_ a value.
  + [x] **`if`** there is no encryption key(s)
+ [x] **`encrypt/1`** encrypts the **`:name_plaintext`** using **`AES256GCM`** and the _latest_ Encryption Key.
see: https://github.com/dwyl/phoenix-ecto-encryption-example#31-encrypt
+ [x] **`decrypt/2`** accepts a the **`ciphertext`** and **`key_id`** as parameters and returns the decrypted **`String`**.
see: https://github.com/dwyl/phoenix-ecto-encryption-example#32-decrypt

Required for/by: 
+ [x] Name Field: https://github.com/dwyl/fields/issues/11

**Comment by nelsonic** [comment]
https://github.com/dwyl/fields/blob/43f15171df363fa7f71ce14e36f44be41916b332/lib/aes.ex#L31-L41

https://github.com/dwyl/fields/blob/43f15171df363fa7f71ce14e36f44be41916b332/lib/aes.ex#L56-L61

Done. 👍 
Thanks @Danwhy 🎉
