### ISSUE TITLE
Create :name Binary Field 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/fields#11]
As a developer building Apps/APIs I would like to address the person using their name e.g: "Hi Alex,"<sup>1</sup>
in both my App and when sending them an Email, 
so that the communication feels more _personal_ and they feel more _engaged_/_welcome_. 

To this end, we need to _securely_ store (_encrypt_) the person's name in the Database when they register.

# Prerequisites 

+ [ ] To _understand_ this issue/story, please ensure you have read/followed: https://github.com/dwyl/phoenix-ecto-encryption-example
_everything_ will "make sense" once you've followed the example.
(_and if **anything** is **unclear**, please open a question/issue in that repo. thanks!_)

> One of the _major_ goals of the **`fields`** module/package is to make creating _secure_ apps (_where people's personal data is transparently encrypted/decrypted_) as _easy_ for beginners as possible!
> So we need to _all_ have a _very_ clear understanding of the "basics" of Hashing/Encryption before diving in to implementing re-useable fields and corresponding Custom Ecto Types here. 
> These field definitions will be used in/by [**`autoform`**](https://github.com/dwyl/autoform) to easily render UI. 

# Todo

Define the following fields (Custom Ecto Types):

+ [ ] **`:name`** (`Binary`) field for storing the person's name _encrypted_ in the database.
  + [x] the Custom Ecto Type should implement the **4 "callback" functions** using the helper functions https://github.com/dwyl/fields/issues/10 see: https://github.com/dwyl/phoenix-ecto-encryption-example#4-create-encryptedfield-custom-ecto-type
  + [x] When an _encrypted_ field is stored in a Database it, the encryption key ID should be stored _with_ the data so that we can easily decrypt it.<sup>2</sup>

+ [ ] **`:name_plaintext`** (plaintext `String` "_virtual_") field should be used by [**`autoform`**](https://github.com/dwyl/autoform) UI where the end-user will enter their Name and received on the Server to distinguish it in the [**`changeset`**](https://hexdocs.pm/ecto/Ecto.Changeset.html). 
  > The **`:name_plaintext`** field should _never_ be stored in the DB. it should only ever be defined as a "virtual" field in any schema that uses it.<sup>3</sup>. see: https://hexdocs.pm/ecto/Ecto.Schema.html

<sup>1</sup> best way to address a person in an email: https://www.businessinsider.com/the-perfect-way-to-start-an-email-and-greetings-you-should-avoid-2016-5#winner-hi-name--1

<sup>2</sup>Storing encryption key IDs in the database with along with the encrypted _value_ (binary data) is _essential_ for ensuring that we can _decrypt_ the value. I am "torn" between the following **two options**: 

A.  Add an **`:encryption_key_id`** field to the Schema in [**`alog`**](https://github.com/dwyl/alog) such that the encryption key id is only stored _once_ per "row" of data and all sensitive data in that row is encrypted using that key. 

B. ***Prepend*** the encryption key id to _each_ item of data when it gets encrypted such that every piece of data that is stored encrypted has the following format: `{encryption_key_id}|{encrypted_data}`
e.g: `1|5IFabJBxvJfGbrb40g3jU5dl8v46WZj0gyVSEdrGxBtKYuzPRHQO3DVjMUfuUNH` where the id of the encryption key is **`1`** and the [ciphertext](https://en.wikipedia.org/wiki/Ciphertext) is `5IFabJB...`

At the moment I'm tending towards "Option B" so that we can "_decouple_" the encryption from storage. https://en.wikipedia.org/wiki/Coupling_(computer_programming)

<sup>3</sup>I do not envisage us _ever_ storing a person's Name as "plaintext". 
If anyone can think of a reason to store this data as a String instead of as Binary, please share!

**Comment by nelsonic** [comment]
https://www.w3.org/International/questions/qa-personal-names

**Comment by nelsonic** [comment]
Going with max name length 35 characters. 
see: https://stackoverflow.com/questions/20958/list-of-standard-lengths-for-database-fields

**Comment by nelsonic** [comment]
Implemented in PR #59 ✅
