### ISSUE TITLE
Create :email_encrypted Binary and :email_hash Binary Fields 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/fields#12]
As a developer building web Apps/APIs where people's personal data will be stored,
I need to store email addresses both (a) hashed and (b) encrypted  **so that** emails can be: 
+ (a) indexed and looked up fast [during login] and 
+ (b) ***decrypted*** back into plaintext so we can send the person a notification/reset password email.

# Todo 

+ [x] based on the example in: https://github.com/dwyl/phoenix-ecto-encryption-example#5-use-encryptedfield-ecto-type-in-user-schema create:
  + [x] **`:email_encrypted`** (`Binary`) - this will be "reversible" using the **`decrypt/1`** helper #10
  + [x] **`:email_hash`** (`Binary`) using the `hash/1` helper function #10
  + [x] **`:email_plaintext`** (`String` "_virtual_") field will be displayed in the UI when [**`autoform`**](https://github.com/dwyl/autoform) renders this field. 
+ [x] **`:email_plaintext`** should be rendered as [**`<input type="email">`**](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email) by [**`autoform`**](https://github.com/dwyl/autoform) so that browsers will perform client-side validation.
+ [x] Email address should be _validated_ using a regular expression. 
  + [x] Invalid email address should return and **Error** which **`autoform`** will display.

**Comment by nelsonic** [comment]
+ https://github.com/dwyl/fields/blob/master/lib/email_hash.ex
+ https://github.com/dwyl/fields/blob/master/lib/email_encrypted.ex
created by @Danwhy ✅
