### ISSUE TITLE
Create :password String and :password_hash Binary Fields 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/fields#13]
As a developer who wants to create a web apps that allow people to login,
I need to store _hashed_ passwords securely in a database,
so that the password can be verified when the person attempts to login
(_and invalid login attempts can be rejected_).

# Todo

+ [x] Inspired by https://github.com/dwyl/phoenix-ecto-encryption-example#35-hash-password  create 
  + [x] a Custom Ecto Type that defines a **`:password_hash`** (`Binary`) field. 
     + [x] implement the 4 callback functions using the helper functions #10
  + [x] We may need to have a "virtual" **`:password`** field to use in the changeset so that we don't "_confuse_" people as to what the original "plaintext" (_unhashed_) password was.
see: https://github.com/dwyl/phoenix-ecto-encryption-example#102-re-order-email_hash-field-in-user-schema
+ [x] the **`:password`** `String` should be hashed using **`Argon2id`** before inserting it into a database<sup>1</sup>
+ [x] When a lookup is performed to verify a password, the `verify_password/2` should be used to compare the **`:password`** (`String`) as input by the person in the form against the **`:password_hash`** (`Binary`) stored in the DB.<sup>2</sup>**Note**:
see: https://github.com/dwyl/phoenix-ecto-encryption-example#36-verify-password
+ [x] An [**`<<input type="password">`**](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password) should be rendered when this field is displayed in an [**`autoform`**](https://github.com/dwyl/autoform)

<sup>1</sup>**Note**: this is _not_ where we are creating the password reset functionality, 
we will _use_ **`Fields.password`** in **`Auth`** 

<sup>2</sup>**Note**: we do not _need_ to _store_ the **`:password_hash`** in a Database for the purposes of writing/testing the **`Fields.password_hash`** field. But if you decide to write a more "real world" test, we will need to implement the

**Comment by nelsonic** [comment]
Implemented in #4 by @Danwhy 🥇
