### ISSUE TITLE
Create :url & :url_encrypted Field to store Website Addresses & Links

### ISSUE THREAD

**Issue by nelsonic** [dwyl/fields#16]
As a developer building web Apps/APIs where people want to share & display links to websites,
I need to _validate_ and store **URL**s (_both plaintext & encrypted_).

# Todo 

+ [x] **`:url`** (`String`) for URLs that _don't_ need to be encrypted (_this is a perfectly valid use-case_)
+ [x] **`:url_encrypted`** (`Binary`) - encrypted using the **`encrypt/1`** helper and "reversible" using the **`decrypt/1`** helper #10 
+ [x] Create a `Fields.validate_url` function that _validates_ URLs using a standards-complaint RegEx 
  e.g: https://mathiasbynens.be/demo/url-regex
+ [x] Invalid URLS should return and **Error** which **`autoform`** will display in the frontend.

**Comment by Cleop** [comment]
Within the validation regex we should ensure that `http://` / `https://` are compulsory because otherwise the links don't won't take you to external sites.

**Comment by nelsonic** [comment]
@Cleop we should not require the protocol when validating a URL.
but perhaps in future we could display a _warning_ if `https` is not used.

**Comment by Cleop** [comment]
@nelsonic - ok that sounds like a good idea. I presume that is something which would be application specific rather than something built into the Fields repo? 

From what I could understand of the link you shared on regex validation, it appeared to show a number of different possible validation styles. Do you have any preference of one to choose or shall I do some research and suggest one which seems good to me? I don't without doing more research have an immediate instinct on this...

**Comment by nelsonic** [comment]
@Cleop for now just validate the URL using @diegoperini's RegEx. (_No need to warn when not https_)

The RegEx is _super_ long but it validates the _most_ URLs according to https://mathiasbynens.be/demo/url-regex (_as linked to above_):
```
_^(?:(?:https?|ftp)://)(?:\S+(?::\S*)?@)?(?:(?!10(?:\.\d{1,3}){3})(?!127(?:\.\d{1,3}){3})(?!169\.254(?:\.\d{1,3}){2})(?!192\.168(?:\.\d{1,3}){2})(?!172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})(?:[1-9]\d?|1\d\d|2[01]\d|22[0-3])(?:\.(?:1?\d{1,2}|2[0-4]\d|25[0-5])){2}(?:\.(?:[1-9]\d?|1\d\d|2[0-4]\d|25[0-4]))|(?:(?:[a-z\x{00a1}-\x{ffff}0-9]+-?)*[a-z\x{00a1}-\x{ffff}0-9]+)(?:\.(?:[a-z\x{00a1}-\x{ffff}0-9]+-?)*[a-z\x{00a1}-\x{ffff}0-9]+)*(?:\.(?:[a-z\x{00a1}-\x{ffff}]{2,})))(?::\d{2,5})?(?:/[^\s]*)?$_iuS
```
We should put that into a `url/1` function in the [`lib/validate.ex`](https://github.com/dwyl/fields/blob/master/lib/validate.ex) file.
And add a few `doctest` comments above it to validate inline. 
If you need _inspiration_ for doctests see: 
https://github.com/multiformats/ex_multihash/blob/dd3ce7e39d053049dbd7219c2aba2dbde9940bb2/lib/multihash.ex#L54-L58
If you get "_stuck_", _please_ open an issue on learn-elixir so we can capture the learning. 👍

**Comment by Cleop** [comment]
### Note
In order for this regex to work in elixir a couple of changes had to be made:

- all instances of `\.` had to have another backslash added to look like : `\\.`
- The `_` at the very beginning and the `_iuS` at the end of the regex had to be removed

**Comment by diegoperini** [comment]
The person you are referring to is @dperini, who has the same name as mine accidentally.

**Comment by nelsonic** [comment]
PR: https://github.com/dwyl/fields/pull/59 🔜
