### ISSUE TITLE
Create :phone_number & :phone_number_encrypted Fields 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/fields#17]
As a developer building web Apps/APIs where people want to capture & display Phone Numbers,
I need to _validate_ and store **Phone Numbers** (_both as plaintext & encrypted_).

# Todo 

+ [ ] **`:phone_number`** (`String`) for Phone Numbers that _don't_ need to be encrypted (_this is a perfectly valid use-case e.g for a Venue/Place where phone numbers are "public knowledge"_)
+ [ ] **`:phone_number_encrypted`** (`Binary`), for when the Phone Number is "Personally Identifiable Information" (PII) should be encrypted using the **`encrypt/1`** helper and "reversible" using the **`decrypt/1`** helper #10 
+ [ ] Create a `Fields.validate_phone_number` function that _validates_ Phone Numbers using a standards-complaint RegEx 
  e.g: https://stackoverflow.com/questions/123559/a-comprehensive-regex-for-phone-number-validation
+ [ ] Invalid Phone Numbers should return and **Error** which **`autoform`** will display in the frontend.
+ [ ] _Ideally_ phone numbers should be rendered in such a way that when clicked/tapped they should launch a Phone "App" so that Users can tap-to-call any number displayed on a Web/App.
see: https://stackoverflow.com/questions/1608548/how-to-trigger-a-phone-call-when-clicking-a-link-in-a-web-page-on-mobile-phone

**Comment by nelsonic** [comment]
+ https://github.com/dwyl/fields/blob/master/lib/phone_number.ex
+ https://github.com/dwyl/fields/blob/master/lib/phone_number_encrypted.ex

✅ @Danwhy 🚀
