### ISSUE TITLE
Create :postcode & :postcode_encrypted Fields

### ISSUE THREAD

**Issue by nelsonic** [dwyl/fields#18]
As a developer building web Apps/APIs where people want to capture & display **Postcodes**,
I need to _validate_ and store **Postcodes** (_both as plaintext & encrypted_).

# Todo 

+ [ ] **`:postcode`** (`String`) for Postcodes that _don't_ need to be encrypted (_e.g for a Venue/Place where the address is "public knowledge", there's no need to encrypt it_)
+ [ ] **`:postcode_encrypted`** (`Binary`), for when the Postcode is "Personally Identifiable Information" (PII) should be encrypted using the **`encrypt/1`** helper and "reversible" using the **`decrypt/1`** helper #10 
+ [ ] Create a `Fields.validate_postcode/1` function that _validates_ Postcodes using a standards-complaint RegEx 
  e.g: https://stackoverflow.com/questions/164979/uk-postcode-regex-comprehensive
 >  **Note**: we can _extend_ this later to a `Fields.validate_postcode/2` where the _second_ argument is a "region" (_country code_) such that we can validate a `US` postcode `90210` which is a _very_ different format from a `UK` one e.g: `SW1A 0AA`
+ [ ] Invalid Postcodes should return and **Error** which **`autoform`** will display in the frontend.
+ [ ] _Ideally_ postcodes should be rendered in such a way that when clicked/tapped they should launch a "Maps App" so that Users can tap any postcode displayed on a Web/App to navigate to the address. We should gain this knowledge from #17

**Comment by Danwhy** [comment]
@nelsonic for the validation of the postcode, do we care if it's an _existing_ postcode, or is it enough that the postcode is in a _valid format_? There's a lot of discussion on that stack overflow question and elsewhere as to what exactly the most comprehensive postcode regex is.

**Comment by nelsonic** [comment]
@Danwhy indeed there is _always_ "_debate_" around the "_perfect_" RegEx ... 
we just need to _start_ with something that will meet our _current_ needs.
If it successfully "_accepts_" (_validates_) a "real" postcode e.g: `SW1X 8RX` during the demo and initial user testing, and "_rejects_" (_as invalid_) a "fake" postcode like "Hello" or "test", then I will _personally_ be happy. 

We can _evolve_ this later in future iterations. 👍 

Thanks! ✨

**Comment by nelsonic** [comment]
+ https://github.com/dwyl/fields/blob/master/lib/postcode.ex
+ https://github.com/dwyl/fields/blob/master/lib/postcode_encrypted.ex
Implemented in #22 by @Danwhy 🎉
