### ISSUE TITLE
Create :address & :address_encrypted Fields

### ISSUE THREAD

**Issue by nelsonic** [dwyl/fields#21]
As a developer building web Apps/APIs where people want to capture & display their **Address**,
I need to an [**`<textarea>`**](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea) field that will accept an **`Address`**, _validate_ and store it (_both as plaintext & encrypted_).

# Todo 

+ [x] **`:address`** (`String`) for Addresses that _don't_ need to be encrypted (_e.g for a Venue/Place where the address is "public knowledge", there's no need to encrypt it and having it **searchable** is a good idea!_)
+ [x] **`:address_encrypted`** (`Binary`), for when the Address is "Personally Identifiable Information" (PII) should be encrypted using the **`encrypt/1`** helper and "reversible" using the **`decrypt/1`** helper #10 
+ [x] Create a `Fields.validate_address/1` function that _loosely validates_ the Address using a _permissive_ RegEx (_cannot be too "strict" until we have a decent amount of valid data to "train" it_)
  + [x] `#HelpWanted` researching & defining the RegEx! Note that there is a _wide_ range of _valid_ addresses, so we may need to base this validation purely on `String.length` initially ... 🤔 
+ [x] Invalid Address should return and **Error** which **`autoform`** will display in the frontend.
+ [x] _Ideally_ Address should be rendered in such a way that when clicked/tapped they should launch a "Maps App" so that Users can tap any postcode displayed on a Web/App to navigate to the address. We should gain this knowledge from #18 

# Question for Discussion: _One_ Field for _Whole_ Address?

As a Developer, I would like to make the Address Field as _frictionless_ as possible for data collection,
and not require the user to enter data into _multiple_ fields.
_However_ I _acknowledge_ that people might be _accustomed_ to having **address_line_1**,  **address_line_2**, etc. in e-commerce forms ... 

What I'm _proposing_ is that `Fields.address` is _rendered_ as [**`<textarea>`**](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea) so the person is free to _multi-line_ their address if they need to, but it's stored in the DB with the line breaks converted to `\n` (_or whatever the cross-platform line-break character needs to be_)

What is the "Material Design" UX Pattern and can we "_question_" it in the name of _MVP simplicity_? 
(_research required, any volunteers?_) 

Thankfully the https://material.io/design/components/text-fields.html#usage appears to be on the side of _reason/simplicity_: (_so it's unlikely we'll need to to "fight" any "PO" on this..._) 
![image](https://user-images.githubusercontent.com/194400/48281346-330ef380-e44e-11e8-90bf-9ff826c61a87.png)

# Useful/Background reading:

+ How to store the address: https://stackoverflow.com/questions/310540/best-practices-for-storing-postal-addresses-in-a-database-rdbms

**Comment by nelsonic** [comment]
+ [x] https://github.com/dwyl/fields/blob/master/lib/address.ex 
+ [x] https://github.com/dwyl/fields/blob/master/lib/address_encrypted.ex

Thanks @Danwhy 🥇
