### ISSUE TITLE
Docs! 📝 |> 📦 |> 🚀

### ISSUE THREAD

**Issue by nelsonic** [dwyl/fields#52]
At present the **`code`** is good 👍 but the [docs](https://github.com/dwyl/fields/tree/06aa7469a0eebe8cbaacafd2361fcdb4ad76c489) are incomplete  ... which makes using the project harder 😞 

We need to tidy up the docs _both_ the `README.md` and `@doc` comments so that:
**a.** we (@dwyl) can refer to _ourselves_ internally and not waste time scratching our heads. https://github.com/dwyl/app/issues/250
**b.** we can ***publish*** the Hex.pm package so that other people in the Elixir/Phoenix community can ***`use`*** it!
**c.** people can _understand_ how to use the code and **_contribute_ improvements** / new field definitions.
 
# Todo 
+ [x] Add answers to standard "Why? What? Who? How?" questions https://github.com/dwyl/fields/issues/9
+ [x] Review _all_ functions in `/lib` and ensure that **`@doc`** comments are present.
  + [x] if a function is undocumented, add a **`@doc`** comment and write it!
+ [x] Instructions for Environment Variables: https://github.com/dwyl/fields/issues/36
+ [x] Generate Hex Docs on `localhost` to review them ***`before`*** publishing. [/code-reuse-hexpm.md#how](https://github.com/dwyl/learn-elixir/blob/code-reuse-publishing-to-hexpm-issue%2395/code-reuse-hexpm.md#how)
+ [x] Publish Hex.pm package https://github.com/dwyl/fields/issues/2
+ [x] Hex.pm badge in readme:
```
![Hex.pm](https://img.shields.io/hexpm/v/fields?color=brightgreen&style=flat-square)
```
![Hex.pm](https://img.shields.io/hexpm/v/fields?color=brightgreen&style=flat-square)

The lack of docs is _my_ fault. Nobody `else` is to "blame" but me. 
The project was my idea. I must set the standard. I'm fixing it _today_!

**Comment by nelsonic** [comment]
Published https://hex.pm/packages/fields/0.1.8 to Hex.pm ahead of breaking change https://github.com/dwyl/fields/pull/55

**Comment by nelsonic** [comment]
Published https://hex.pm/packages/fields/2.0.0 with @SimonLab's #55 (_breaking change_)

**Comment by nelsonic** [comment]
Decent online docs: https://hexdocs.pm/fields/2.0.0/api-reference.html ✅

**Comment by nelsonic** [comment]
Done: https://github.com/dwyl/fields/pull/59 :shipit:
