### ISSUE TITLE
Hash is unsalted ... let's fix that!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/fields#56]
At present our `Fields.Hash.dump` function does not _salt_ the value before hashing:
https://github.com/dwyl/fields/blob/7a42d7892a439db258d373a1826e7a4a298ff2b7/lib/hash.ex#L22-L24

We need to use the `SECRET_KEY_BASE` to salt the hash so that we can still lookup an `email_hash` but an attacker cannot use a rainbow table to brute force the `email_hash` without the `SECRET_KEY_BASE`. 
> Note: this is my fault for not specifying the requirement earlier. 
(_I cannot expect anyone to read my mind..._)

# Todo

+ [ ] Add salt using `SECRET_KEY_BASE` to `Fields.Hash.dump` function 
+ [ ] Ensure that all tests still pass.
+ [ ] Publish new version of package to hex.pm

**Comment by nelsonic** [comment]
Derp. it was there. I'm just tired ...
https://github.com/dwyl/fields/blob/7a42d7892a439db258d373a1826e7a4a298ff2b7/lib/helpers.ex#L22-L25

**Comment by nelsonic** [comment]
The salt is there in the code but the  `secret_key_base` is not exposed in `config.exs` see: https://github.com/dwyl/fields/issues/57
So I _wasn't_ going crazy ... our hash function in https://github.com/dwyl/app-mvp-phoenix was _not_ working!
