### ISSUE TITLE
Update version of html_sanitize_ex to latest (1.4.2)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/fields#88]
`html_sanitize_ex` (v1.4) triggers a bunch of warnings when we are compiling it:
![image](https://user-images.githubusercontent.com/194400/132957906-c2572cf3-ee15-4621-bdd2-b281b441343b.png)

Thankfully a new version was recently released that fixes the `@doc` and updates tests etc.
https://github.com/rrrene/html_sanitize_ex/releases/tag/v1.4.2
![image](https://user-images.githubusercontent.com/194400/132957922-4d506caf-f366-4292-94bf-b7da4874ffaa.png)

# Todo

+ [x] update the version of `html_sanitize_ex` to latest in `mix.exs` and correspondingly `mix.lock`
+ [x] create Pull Request 
+ [x] deploy new version of `fields` (`2.8.1`) to hex.pm so we can use it in our projects

**Comment by SimonLab** [comment]
To see which dependencies can be updated we can use the command: `mix hex.outdated`
![image](https://user-images.githubusercontent.com/6057298/135251206-964cb1ce-de89-475e-8a42-2ecbf6168b8b.png)

**Comment by nelsonic** [comment]
Package published to https://hex.pm/packages/fields/2.8.1 📦 
Thanks @SimonLab 🙌
